<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ProxiEat | Feeder F-003</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <link href="assets/css/dashboard.css" rel="stylesheet">
    <link href="assets/css/feeders.css" rel="stylesheet">
</head>
<body>
    <div class="app-shell d-flex">
        <aside class="sidebar d-flex flex-column">
            <div class="brand d-flex align-items-center gap-2 px-4 py-4"><span class="brand-mark"><i class="bi bi-heart-pulse-fill"></i></span><span>ProxiEat</span></div>
            <nav class="nav flex-column px-3 gap-1"><a class="nav-link" href="index.php"><i class="bi bi-grid-1x2-fill"></i> Dashboard</a><a class="nav-link" href="pet_boarding.php"><i class="bi bi-house-heart"></i> Pet Boarding</a><a class="nav-link" href="pet_management.php"><i class="bi bi-heart"></i> Pets</a><a class="nav-link" href="owner_management.php"><i class="bi bi-people"></i> Pet Owners</a><a class="nav-link active" href="pet_feeders.php"><i class="bi bi-egg-fried"></i> Pet Feeders</a><a class="nav-link" href="#"><i class="bi bi-calendar-check"></i> Feeding Schedule</a><a class="nav-link" href="#"><i class="bi bi-camera-video"></i> Camera Monitoring</a><a class="nav-link" href="#"><i class="bi bi-file-earmark-bar-graph"></i> Reports</a><a class="nav-link" href="#"><i class="bi bi-gear"></i> Settings</a></nav>
        </aside>
        <div class="content-wrap flex-grow-1">
            <nav class="topbar navbar bg-white border-bottom px-3 px-lg-4"><h1 class="h5 mb-0 fw-semibold text-dark">Feeder Details</h1><div class="d-flex align-items-center gap-3"><button class="btn btn-light position-relative rounded-circle notification-btn"><i class="bi bi-bell fs-5"></i><span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">3</span></button><div class="dropdown"><button class="btn profile-button dropdown-toggle d-flex align-items-center gap-2" data-bs-toggle="dropdown"><img src="https://i.pravatar.cc/80?img=47" alt="Front Desk Staff" class="profile-photo"><span class="d-none d-sm-inline fw-semibold small">Front Desk Staff</span></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="#">Profile</a></li><li><a class="dropdown-item" href="#">Settings</a></li><li><a class="dropdown-item text-danger" href="#">Logout</a></li></ul></div></div></nav>
            <main class="dashboard-content p-3 p-md-4">
                <a href="pet_feeders.php" class="btn btn-sm btn-link text-decoration-none px-0 mb-3"><i class="bi bi-arrow-left me-1"></i>Back to Pet Feeders</a>
                <section class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h2 class="h3 fw-bold mb-1">Feeder F-003</h2><p class="text-muted mb-1">Assigned to: <strong class="text-dark">Buddy</strong> <span class="mx-1">•</span> Golden Retriever <span class="mx-1">•</span> Room 05</p><span class="badge status-assigned">Assigned</span></div><button class="btn btn-outline-primary align-self-md-start"><i class="bi bi-pencil me-1"></i>Edit Feeder</button></section>
                <section class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="card detail-stat h-100"><div class="card-body"><span class="summary-icon orange"><i class="bi bi-box-seam"></i></span><p class="summary-label">Food Tank Level</p><h3>82%</h3><div class="progress"><div class="progress-bar food" style="width:82%"></div></div></div></div></div><div class="col-6 col-xl-3"><div class="card detail-stat h-100"><div class="card-body"><span class="summary-icon blue"><i class="bi bi-droplet-fill"></i></span><p class="summary-label">Water Tank Level</p><h3>64%</h3><div class="progress"><div class="progress-bar water" style="width:64%"></div></div></div></div></div><div class="col-6 col-xl-3"><div class="card detail-stat h-100"><div class="card-body"><span class="summary-icon green"><i class="bi bi-basket2-fill"></i></span><p class="summary-label">Remaining Food</p><h3>420 g</h3><p class="summary-note">Estimated 4 meals remaining</p></div></div></div><div class="col-6 col-xl-3"><div class="card detail-stat h-100"><div class="card-body"><span class="summary-icon blue"><i class="bi bi-check2-circle"></i></span><p class="summary-label">Today's Feedings</p><h3>2 of 4</h3><p class="summary-note">Completed</p></div></div></div></section>
                <section class="row g-4 mb-4"><div class="col-lg-6"><div class="card h-100"><div class="card-body p-4"><h3 class="profile-section-title">Assigned Pet</h3><div class="d-flex gap-3 align-items-center mt-3"><img src="https://i.pravatar.cc/100?img=12" class="rounded-circle owner-photo" style="width:64px;height:64px" alt="Buddy"><div><h4 class="h5 mb-1">Buddy</h4><p class="text-muted mb-0 small">Golden Retriever • Male</p></div></div><div class="row mt-3"><div class="col-6"><p class="info-label">Owner</p><p class="info-value">John Reyes</p><p class="info-label">Room Number</p><p class="info-value mb-0">Room 05</p></div><div class="col-6"><p class="info-label">Check-in</p><p class="info-value">Jul 23, 2026</p><p class="info-label">Check-out</p><p class="info-value mb-0">Jul 28, 2026</p></div></div><a href="pet_management.php" class="btn btn-outline-primary btn-sm mt-3">View Pet Profile</a></div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-body p-4"><h3 class="profile-section-title">Feeding Schedule</h3><div class="list-group list-group-flush mt-2"><div class="list-group-item px-0 d-flex align-items-center"><strong class="schedule-time">8:00 AM</strong><span class="badge text-bg-success">Completed</span></div><div class="list-group-item px-0 d-flex align-items-center"><strong class="schedule-time">12:00 PM</strong><span class="badge text-bg-success">Completed</span></div><div class="list-group-item px-0 d-flex align-items-center"><strong class="schedule-time">5:00 PM</strong><span class="badge status-maintenance">Upcoming</span></div><div class="list-group-item px-0 d-flex align-items-center"><strong class="schedule-time">9:00 PM</strong><span class="badge status-maintenance">Upcoming</span></div></div></div></div></div></section>
                <section class="card mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h3 class="profile-section-title mb-0 border-0 p-0">Portion Control</h3><button class="btn btn-outline-primary btn-sm"><i class="bi bi-pencil me-1"></i>Edit Feeding Schedule</button></div><div class="row text-center g-3"><div class="col-6 col-md-3"><p class="text-muted small mb-1">Breakfast</p><strong>120 g</strong></div><div class="col-6 col-md-3"><p class="text-muted small mb-1">Lunch</p><strong>100 g</strong></div><div class="col-6 col-md-3"><p class="text-muted small mb-1">Dinner</p><strong>120 g</strong></div><div class="col-6 col-md-3"><p class="text-muted small mb-1">Night Meal</p><strong>80 g</strong></div></div><div class="border-top mt-3 pt-3 text-center"><span class="text-muted me-2">Daily Total</span><strong class="text-primary">420 g</strong></div></div></section>
                <section class="card mb-4"><div class="card-body p-4"><h3 class="profile-section-title">Camera Preview</h3><div class="camera-placeholder rounded-3 mt-3"><i class="bi bi-camera-video fs-1 mb-2"></i><span>Feeder camera preview</span></div><div class="d-flex gap-2 mt-3"><button class="btn btn-primary"><i class="bi bi-play-circle me-1"></i>Open Live Camera</button><button class="btn btn-outline-secondary"><i class="bi bi-camera me-1"></i>Capture Snapshot</button></div></div></section>
                <section class="card mb-4"><div class="card-body p-4"><h3 class="profile-section-title">Recent Activity</h3><div class="row g-3 mt-1"><div class="col-md-6"><div class="d-flex gap-2"><span class="activity-icon"><i class="bi bi-basket2"></i></span><div><strong class="small">08:00 AM — Food Dispensed</strong><p class="text-muted small mb-0">Breakfast portion delivered.</p></div></div></div><div class="col-md-6"><div class="d-flex gap-2"><span class="activity-icon"><i class="bi bi-heart-fill"></i></span><div><strong class="small">08:02 AM — Pet Started Eating</strong><p class="text-muted small mb-0">Buddy began breakfast.</p></div></div></div><div class="col-md-6"><div class="d-flex gap-2"><span class="activity-icon"><i class="bi bi-check-circle"></i></span><div><strong class="small">08:09 AM — Pet Finished Eating</strong><p class="text-muted small mb-0">Breakfast completed.</p></div></div></div><div class="col-md-6"><div class="d-flex gap-2"><span class="activity-icon"><i class="bi bi-basket2"></i></span><div><strong class="small">12:00 PM — Food Dispensed</strong><p class="text-muted small mb-0">Lunch portion delivered.</p></div></div></div><div class="col-md-6"><div class="d-flex gap-2"><span class="activity-icon"><i class="bi bi-droplet"></i></span><div><strong class="small">02:30 PM — Water Refilled</strong><p class="text-muted small mb-0">Water tank topped up.</p></div></div></div></div></div></section>
                <section class="card"><div class="card-body p-4"><h3 class="profile-section-title">Quick Actions</h3><div class="d-flex flex-wrap gap-2 mt-3"><button class="btn btn-primary"><i class="bi bi-basket2 me-1"></i>Dispense Food Now</button><button class="btn btn-outline-warning"><i class="bi bi-bell me-1"></i>Refill Reminder</button><button class="btn btn-outline-primary"><i class="bi bi-pencil me-1"></i>Edit Feeder</button><button class="btn btn-outline-danger"><i class="bi bi-x-circle me-1"></i>Unassign Feeder</button></div></div></section>
            </main>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
